### ISSUE TITLE
undefined symbol: GOMP_parallel

### ISSUE THREAD

**Issue by wlixin** [rmjarvis/TreeCorr#58]
I have install the package successfully, however when I try to import the package, there is a issue as 
below:
 import treecorr     
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/treecorr/__init__.py", line 41, in <module>
    _lib = _ffi.dlopen(lib_file)
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 139, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 769, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 758, in _load_backend_lib
    return backend.load_library(name, flags)
OSError: cannot load library /home/wlixin/anaconda2/lib/python2.7/site-packages/treecorr/_treecorr.so: /home/wlixin/anaconda2/lib/python2.7/site-packages/treecorr/_treecorr.so: undefined symbol: GOMP_parallel

**Comment by rmjarvis** [comment]
It looks like you have treecorr installed in two different places that are incompatible with each other.  The traceback includes
```
File "/usr/local/lib/python2.7/dist-packages/treecorr/init.py", line 41, in 
_lib = _ffi.dlopen(lib_file)
```
but then the library it is trying to open is in your home directory
```
OSError: cannot load library /home/wlixin/anaconda2/lib/python2.7/site-packages/treecorr/_treecorr.so: /home/wlixin/anaconda2/lib/python2.7/site-packages/treecorr/_treecorr.so: undefined symbol: GOMP_parallel
```
My guess is you installed one one way (e.g. python setup.py install) and then the other a different way (e.g. pip install treecorr) and the second one didn't completely clean up after the first one and left something that isn't quite correct. 

You may just need to delete whichever one is the old one.  Or maybe delete both and try reinstalling from scratch.

**Comment by rmjarvis** [comment]
Assuming from lack of response that the problem is resolved by the above comment.  Please reopen with more details if this is not the case.

**Comment by aimerson** [comment]
Hi -- following through the instructions in this thread I still get a similar error. Here is the traceback:

`[amerson@comet-ln2 ~]$ pip install treecorr
Collecting treecorr
Requirement already satisfied: pyyaml in ./software/anaconda2/lib/python2.7/site-packages (from treecorr)
Requirement already satisfied: fitsio in ./software/anaconda2/lib/python2.7/site-packages (from treecorr)
Requirement already satisfied: pandas in ./software/anaconda2/lib/python2.7/site-packages (from treecorr)
Requirement already satisfied: numpy in ./software/anaconda2/lib/python2.7/site-packages (from treecorr)
Requirement already satisfied: future in ./software/anaconda2/lib/python2.7/site-packages (from treecorr)
Requirement already satisfied: cffi in ./software/anaconda2/lib/python2.7/site-packages (from treecorr)
Requirement already satisfied: pytz>=2011k in ./software/anaconda2/lib/python2.7/site-packages (from pandas->treecorr)
Requirement already satisfied: python-dateutil>=2.5.0 in ./software/anaconda2/lib/python2.7/site-packages (from pandas->treecorr)
Requirement already satisfied: pycparser in ./software/anaconda2/lib/python2.7/site-packages (from cffi->treecorr)
Requirement already satisfied: six>=1.5 in ./software/anaconda2/lib/python2.7/site-packages (from python-dateutil>=2.5.0->pandas->treecorr)
Installing collected packages: treecorr
Successfully installed treecorr-3.3.11
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[amerson@comet-ln2 ~]$ python
Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import treecorr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amerson/software/anaconda2/lib/python2.7/site-packages/treecorr/__init__.py", line 41, in <module>
    _lib = _ffi.dlopen(lib_file)
  File "/home/amerson/software/anaconda2/lib/python2.7/site-packages/cffi/api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/home/amerson/software/anaconda2/lib/python2.7/site-packages/cffi/api.py", line 802, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/home/amerson/software/anaconda2/lib/python2.7/site-packages/cffi/api.py", line 797, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library '/home/amerson/software/anaconda2/lib/python2.7/site-packages/treecorr/_treecorr.so': /home/amerson/software/anaconda2/lib/python2.7/site-packages/treecorr/_treecorr.so: undefined symbol: GOMP_parallel.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/home/amerson/software/anaconda2/lib/python2.7/site-packages/treecorr/_treecorr.so'`

**Comment by rmjarvis** [comment]
Another thing to look for is two different gcc libraries.  For instance, anaconda sometimes has its own version of gcc installed, which may not be equivalent to the native one on your system. If one version of gcc was used to compile treecorr, and a different libgcc is loaded at runtime, then you can get this kind of error.  

One way this can manifest is through an incompatibility between your LD_LIBRARY_PATH and what anaconda is expecting.  You may have another libgcc found earlier in the path than the one corresponding to anaconda's gcc.

Sometimes all of this can be solved by doing `conda install gcc` explicitly to get it first in line of multiple gcc options.  I think this updates your LD_LIBRARY_PATH accordingly.  Probably want to do this within a conda environment, so you can easily switch it on and off (via `conda activate`).

**Comment by aimerson** [comment]
Ok, that could well be the case as I regularly work with another code with a specific set of dependencies. I will try to install the anaconda version of gcc in a condo environment (though at the moment I am unable to activate condo environments without root access).

Is there a way to reinstall treecorr and tell pip explicitly which version of gcc to use?

**Comment by rmjarvis** [comment]
I believe pip respects the CC environment variable.  So you can do
```
pip uninstall treecorr
CC=/path/to/gcc pip -v install --no-cache-dir treecorr
```
The `--no-cache-dir` tells it not to just notice the previously installed version in your cache, and to actually recompile the code instead.

**Comment by rmjarvis** [comment]
If the compiler is using a different OMP library than the loader finds at run time (cf. LD_LIBRARY_PATH and DYLD_LIBRARY_PATH), then you can get this error.  I'm sorry, but I probably cannot diagnose this for you.  My best guess is that you have an incompatibility in the gcc (and associated omp library) at compile time than what is being loaded at run time.
